"""relationship changes in job emplyertables

Revision ID: e5cb04c4f9ee
Revises: fe535a24a6cc
Create Date: 2024-07-10 21:31:31.903048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5cb04c4f9ee'
down_revision = 'fe535a24a6cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers_table.id'], name=op.f('fk_jobs_employer_id_employers_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('jobs_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('salary', sa.INTEGER(), nullable=False),
    sa.Column('employer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers_table.id'], name='fk_jobs_table_employer_id_employers_table'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('jobs')
    # ### end Alembic commands ###
