"""empty message

Revision ID: fe535a24a6cc
Revises: 
Create Date: 2024-07-10 14:19:42.492425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe535a24a6cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employers_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_seekers_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employer_job_seekers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('job_seeker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers_table.id'], name=op.f('fk_employer_job_seekers_employer_id_employers_table')),
    sa.ForeignKeyConstraint(['job_seeker_id'], ['job_seekers_table.id'], name=op.f('fk_employer_job_seekers_job_seeker_id_job_seekers_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_seekers_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_url', sa.String(), nullable=False),
    sa.Column('skills', sa.String(), nullable=False),
    sa.Column('education_level', sa.String(), nullable=False),
    sa.Column('work_experience', sa.String(), nullable=False),
    sa.Column('portfolio_url', sa.String(), nullable=False),
    sa.Column('jobseeker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jobseeker_id'], ['job_seekers_table.id'], name=op.f('fk_job_seekers_details_jobseeker_id_job_seekers_table')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jobseeker_id')
    )
    op.create_table('jobs_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers_table.id'], name=op.f('fk_jobs_table_employer_id_employers_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs_table')
    op.drop_table('job_seekers_details')
    op.drop_table('employer_job_seekers')
    op.drop_table('job_seekers_table')
    op.drop_table('employers_table')
    # ### end Alembic commands ###
